# 外部提供
notify:
  proxy: http://10.9.24.190:30581
  wecomToken:

prometheus:
  url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090

outSideMysql:
  enabled: false
  Address:
  User: root
  Pwd: root

outSideRedis:
  enabled: false
  Address:
  User: root
  Pwd: root

# 自定义
initMysql:
  enabled: true

insideMysql:
  enabled: true
  initDb: true
  image: mysql:5.7
  clientImage: mysql:5.7

insideRedis:
  enabled: true
  image: redis:6.2

images:
  nserver: runzhliu/n9e-slim:5.4.1
  nwebapi: runzhliu/n9e-slim:5.4.1
